# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WodyPolskieWMS
                                 A QGIS plugin
 Baza usług WMS publikowanych przez Państwowe Gospodarstwo Wodne Wody Polskie
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-23
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Państwowe Gospodarstwo Wodne Wody Polskie - KZGW - Wydział SIGW
        email                : lukasz.scislowski@wody.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from qgis.PyQt.QtCore import (QCoreApplication, QSettings, Qt, QUrl, QTranslator,
                          QVariant, qVersion)
from qgis.PyQt.QtGui import QDesktopServices
from qgis.PyQt.QtGui import *
from qgis.PyQt.QtWidgets import QAction, QShortcut
from qgis.core import *
from qgis.gui import QgsMessageBar
from qgis.core import QgsProject
from qgis.core import (QgsCoordinateReferenceSystem, QgsCoordinateTransform,
                       QgsCoordinateTransformContext, QgsMapLayerProxyModel,
                       QgsProject)
import json
import locale
import operator
import os
import sys
import time
from collections import OrderedDict
from urllib.request import urlopen

from qgis.PyQt.QtCore import (QCoreApplication, QSettings, Qt, QTranslator,
                          QVariant, qVersion)
from qgis.PyQt.QtGui import *
from qgis.PyQt.QtWidgets import QAction, QShortcut
from qgis.core import *
from qgis.gui import QgsMessageBar
from qgis.core import QgsLayerTreeGroup

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .Wody_Polskie_WMS_dialog import WodyPolskieWMSDialog
import os.path

from .listy_uslug import *

class WodyPolskieWMS:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.project = QgsProject.instance()
        self.wms_mphp_layer = None
        
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'WodyPolskieWMS_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Wody Polskie - Baza WMS')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.project = QgsProject.instance().layerTreeRoot().children()
       
        self.dlg = None
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('WodyPolskieWMS', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Wody_Polskie_WMS/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Wody Polskie - Baza WMS'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Wody Polskie - Baza WMS'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):       
        """Run method that performs all the real work"""
        
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
        
            self.first_start = False
            self.dlg = WodyPolskieWMSDialog()
            #MPHP10k - wywołanie funkcji przycisków
            self.dlg.pbMPHP.clicked.connect(self.add_group_mphp)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_sekcje)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_nazwy_ciek)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_nazwy_jezior)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_wezly_dzial)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_wezly_ciek)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_dzialy)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie1)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie2)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie3)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie4)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie5)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie6)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie7)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie8)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie9)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie10)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie11)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie12)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie13)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlewnie14)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_zlew_element)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_cieki)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_odcinki_ciek)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_cieki_s)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_jeziora)
            self.dlg.pbMPHP.clicked.connect(self.add_wms_mphp_morza)
            
            #Granice PGWWP - wywołanie funkcji przycisku
            #self.dlg.pbPGWWP.clicked.connect(self.add_group_pgwwp)
            self.dlg.pbPGWWP.clicked.connect(lambda: self.add_wms(PGWWP, "PGWWP"))
            #aPGW - wywołanie funkcji przycisków
            #self.dlg.pbaPGW.clicked.connect(self.add_group_apgw)
            self.dlg.pbaPGW.clicked.connect(lambda: self.add_wms(aPGW, "aPGW"))
            #2aPGW - wywołanie funkcji przycisków
            self.dlg.pb2aPGW.clicked.connect(lambda: self.add_wms(aPGW2, "IIaPGW"))            
            #WORP1 - od morza - wywołanie funkcji przycisku
            self.dlg.pbWORP1.clicked.connect(lambda: self.add_wms(worp1, "WORP-ONNP-od morza"))
            #WORP2 - rzeczne - wywołanie funkcji przycisków
            self.dlg.pbWORP2.clicked.connect(lambda: self.add_wms(worp2, "WORP-ONNP-rzeczne"))
            #WORP3 - zniszczenie budowli piętrzących - wywołanie funkcji przycisku
            self.dlg.pbWORP3.clicked.connect(lambda: self.add_wms(worp3, "WORP-ONNP-zniszczenie budowli piętrzących"))
            #WORP4 - Powodzie historyczne, powodzie prawdopodobne - wywołanie funkcji przycisku
            self.dlg.pbWORP4.clicked.connect(lambda: self.add_wms(worp4, "WORP-powodzie historyczne, prawdopodobne"))
            #MZP1 - MZP z głębokością wody 0,2%, raz na 500 lat dla powodzi rzecznych oraz od strony morza - wywołanie funkcji przyciskuw 
            self.dlg.pbMZP1.clicked.connect(lambda: self.add_wms(mzp1, "MZP z głębokością wody-0,2%(raz na 500 lat)"))
            #MZP2 - MZP z głębokością wody 1%, raz na 100 lat dla powodzi rzecznych oraz od strony morza - wywołanie funkcji przycisków 
            self.dlg.pbMZP2.clicked.connect(lambda: self.add_wms(mzp2, "MZP z głębokością wody-1%(raz na 100 lat)"))
            #MZP3 - MZP z głębokością wody 10%, raz na 10 lat - wywołanie funkcji przycisków 
            self.dlg.pbMZP3.clicked.connect(lambda: self.add_wms(mzp3, "MZP z głębokością wody-10%(raz na 10 lat)"))
            #MZP4 - MZP z prędkością przepływu wody 0,2%, raz na 500 lat - wywołanie funkcji przycisków 
            self.dlg.pbMZP4.clicked.connect(lambda: self.add_wms(mzp4, "MZP z prędkością wody-0,2%(raz na 500 lat)"))
            #MZP5 - MZP z prędkością przepływu wody 1%, raz na 100 lat - wywołanie funkcji przycisków 
            self.dlg.pbMZP5.clicked.connect(lambda: self.add_wms(mzp5, "MZP z prędkością wody-1%(raz na 100 lat)"))
            #MZP6 - MZP z prędkością przepływu wody 10%, raz na 10 lat - wywołanie funkcji przycisków 
            self.dlg.pbMZP6.clicked.connect(lambda: self.add_wms(mzp6, "MZP z prędkością wody-10%(raz na 10 lat)"))
            #MZP7 - MZP - całkowite zniszczenie wału przeciwpowodziowego - wywołanie funkcji przycisków 
            self.dlg.pbMZP7.clicked.connect(lambda: self.add_wms(mzp7, "MZP-zniszczenie wału przeciwpowodziowego"))
            #MZP8 - MZP - zniszczenie lub uszkodzenie budowli piętrzącej - wywołanie funkcji przycisków 
            self.dlg.pbMZP8.clicked.connect(lambda: self.add_wms(mzp8, "MZP-zniszczenie lub uszkodzenie budowli piętrzącej"))
            #MZP9 - MZP od strony morza - całkowite zniszczenie wału przeciwsztormowego - wywołanie funkcji przycisków 
            self.dlg.pbMZP9.clicked.connect(lambda: self.add_wms(mzp9, "MZP od strony morza-całkowite zniszczenie wału przeciwsztormowego"))
            #MZP10 - MZP - Obszary szczególnego zagrożenia powodzią
            self.dlg.pbMZP10.clicked.connect(lambda: self.add_wms(mzp10, "MZP-Obszary szczególnego zagrożenia powodzią"))
            #MZP11 - MZP - Mapa orientacyjna
            #self.dlg.pbMZP11.clicked.connect(lambda: self.add_wms(mzp11, "MZP-Mapa orientacyjna"))
            #MRP1 - MRP - MRP 10% potencjalne negatywne konsekwencje dla życia i zdrowia ludzi oraz wartości potencjalnych strat
            self.dlg.pbMRP1.clicked.connect(lambda: self.add_wms(mrp1, "MRP 10% (raz na 10lat) negatywne konsekwencje dla życia i zdrowia ludzi"))
            #MRP2 - MRP - MRP 1% potencjalne negatywne konsekwencje dla życia i zdrowia ludzi oraz wartości potencjalnych strat
            self.dlg.pbMRP2.clicked.connect(lambda: self.add_wms(mrp2, "MRP 1% (raz na 100lat) negatywne konsekwencje dla życia i zdrowia ludzi"))
            #MRP3 - MRP - MRP 0,2% potencjalne negatywne konsekwencje dla życia i zdrowia ludzi oraz wartości potencjalnych strat
            self.dlg.pbMRP3.clicked.connect(lambda: self.add_wms(mrp3, "MRP 0,2% (raz na 500lat) negatywne konsekwencje dla życia i zdrowia ludzi"))
            #MRP4 - MRP - całkowite zniszczenie wału przeciwpowodziowego - potencjalne negatywne skutki dla życia i zdrowia ludzi oraz wartości potencjalnych strat powodziowych
            self.dlg.pbMRP4.clicked.connect(lambda: self.add_wms(mrp4, "MRP-zniszczenie wału przeciwpow.-negatywne skutki dla życia i zdrowia ludzi"))
            #MRP5 - MRP - całkowite zniszczenie wału przeciwsztormowego - potencjalne negatywne skutki dla życia i zdrowia ludzi oraz wartości potencjalnych strat powodziowych
            self.dlg.pbMRP5.clicked.connect(lambda: self.add_wms(mrp5, "MRP-zniszczenie wału przeciwsztorm.-negatywne skutki dla życia i zdrowia ludzi"))
            #MRP6 - MRP 10% negatywne konsekwencje dla środowiska, dziedzictwa kulturowego i działalności gospodarczej
            self.dlg.pbMRP6.clicked.connect(lambda: self.add_wms(mrp6, "MRP 10%(raz na 10lat) negatywne konsekwencje dla środowiska, dziedzictwa kulturowego i działalności gosp."))
            #MRP7 - MRP 1% negatywne konsekwencje dla środowiska, dziedzictwa kulturowego i działalności gospodarczej
            self.dlg.pbMRP7.clicked.connect(lambda: self.add_wms(mrp7, "MRP 1%(raz na 100lat) negatywne konsekwencje dla środowiska, dziedzictwa kult. i działalności gosp."))
            #MRP8 - MRP 0,2% negatywne konsekwencje dla środowiska, dziedzictwa kulturowego i działalności gospodarczej
            self.dlg.pbMRP8.clicked.connect(lambda: self.add_wms(mrp8, "MRP 0,2%(raz na 500lat) negatywne konsekwencje dla środowiska, dziedzictwa kult. i działalności gosp."))
            #MRP9 - MRP - całkowite zniszczenie wału powodziowego - potencjalne negatywne skutki dla środowiska, dziedzictwa kulturowego i działalności gospodarczej
            self.dlg.pbMRP9.clicked.connect(lambda: self.add_wms(mrp9, "MRP-zniszczenie wału przeciwpow.-negatywne skutki dla środowiska, dziedzictwa kult. i działalności gosp."))
            #MRP10 - MRP - całkowite zniszczenie wału powodziowego - potencjalne negatywne skutki dla środowiska, dziedzictwa kulturowego i działalności gospodarczej
            self.dlg.pbMRP10.clicked.connect(lambda: self.add_wms(mrp10, "MRP-zniszczenie wału przeciwsztorm.-negatywne skutki dla środowiska, dziedzictwa kult. i działalności gosp."))
            #MRP11 - MRP-zniszczenie lub uszkodzenie budowli piętrzącej-negatywne skutki dla życia i zdrowia ludzi
            self.dlg.pbMRP11.clicked.connect(lambda: self.add_wms(mrp11, "MRP-zniszczenie lub uszkodzenie budowli piętrzącej-negatywne skutki dla życia i zdrowia ludzi"))
            #MRP12 - MRP-zniszczenie lub uszkodzenie budowli piętrzącej-negatywne skutki dla środowiska, dziedzictwa kult. i działalności gosp.
            self.dlg.pbMRP12.clicked.connect(lambda: self.add_wms(mrp12, "MRP-zniszczenie lub uszkodzenie budowli piętrzącej-negatywne skutki dla środowiska, dziedzictwa kult. i działalności gosp."))
            #PZRP
            self.dlg.pbPZRP.clicked.connect(lambda: self.add_wms(pzrp, "PZRP"))
            #PPSS
            self.dlg.pbPPSS.clicked.connect(lambda: self.add_wms(ppss, "PPSS"))
            
            #Pobieranie danych
            
            #Pobierz geobazę IIaPGW
            self.dlg.pb2aPGW_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/599,baza-danych-przestrzennych-aktualizacji-planow-gospodarowania-wodami/resource/53330/table"))
            #Pobierz geobazę granice PGWWP
            self.dlg.pbPGWWP_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2170,granice-jednostek-panstwowego-gospodarstwa-wodnego/resource/53970"))
            #Pobierz geobazę WORP
            self.dlg.pbWORP_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2181,wstepna-ocena-ryzyka-powodziowego-worp/resource/66358/table"))
            #Pobierz geobazę PZRP
            self.dlg.pbPZRP_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/3591,plany-zarzadzania-ryzykiem-powodziowym-pzrp/resource/54475/table"))
            #Pobierz SHP PPSS - Łączne zagrożenie suszą
            self.dlg.pbPPSS_L_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2784,plan-przeciwdzialania-skutkom-suszy-ppss/resource/42511"))
            #Pobierz SHP PPSS - Zagrożenia suszą atmosferyczną
            self.dlg.pbPPSS_S_A_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2784,plan-przeciwdzialania-skutkom-suszy-ppss/resource/42507"))
            #Pobierz SHP PPSS - Zagrożenia suszą hydrogeologiczną
            self.dlg.pbPPSS_S_HG_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2784,plan-przeciwdzialania-skutkom-suszy-ppss/resource/42508"))
            #Pobierz SHP PPSS - Zagrożenia suszą rolniczą
            self.dlg.pbPPSS_S_R_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2784,plan-przeciwdzialania-skutkom-suszy-ppss/resource/42510"))
            #Pobierz SHP PPSS - Zagrożenia suszą hydrologiczną
            self.dlg.pbPPSS_S_H_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2784,plan-przeciwdzialania-skutkom-suszy-ppss/resource/42509"))
            #Pobierz SHP PPSS - Łączne zagrożenie suszą
            self.dlg.pbPPSS_I_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2784,plan-przeciwdzialania-skutkom-suszy-ppss/resource/42506"))
            #Pobierz SHP MZP - Obszary zagrożenia powodziowego 0,2%
            self.dlg.pbOZP02_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2178,mapa-zagrozenia-powodziowego-mzp/resource/42540"))
            #Pobierz SHP MZP - Obszary zagrożenia powodziowego 1%
            self.dlg.pbOZP1_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2178,mapa-zagrozenia-powodziowego-mzp/resource/42539"))
            #Pobierz SHP MZP - Obszary zagrożenia powodziowego 10%
            self.dlg.pbOZP10_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2178,mapa-zagrozenia-powodziowego-mzp/resource/42538"))
            #Pobierz SHP MZP - Obszary zagrożenia powodziowego w przypadku zniszczenia wału przeciwpowodziowego
            self.dlg.pbOZP_ZWPP_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2178,mapa-zagrozenia-powodziowego-mzp/resource/42541"))
            #Pobierz SHP MZP - Obszary zagrożenia powodziowego od strony morza 0,2%
            self.dlg.pbOZP_M02_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2178,mapa-zagrozenia-powodziowego-mzp/resource/42543"))
            #Pobierz SHP MZP - Obszary zagrożenia powodziowego od strony morza 1%
            self.dlg.pbOZP_M1_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2178,mapa-zagrozenia-powodziowego-mzp/resource/42542"))
            #Pobierz SHP MZP - Obszary zagrożenia powodziowego w przypadku zniszczenia wału przeciwsztormowego
            self.dlg.pbOZP_ZWPS_dane.clicked.connect(lambda: self.open_url("https://dane.gov.pl/pl/dataset/2178,mapa-zagrozenia-powodziowego-mzp/resource/42544"))

            
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
            
    def open_url(self, url):
            QDesktopServices.openUrl(QUrl(url))
            
            
    def add_group_apgw(self):
            global root
            root = QgsProject.instance().layerTreeRoot()
            global aPGW
            aPGW = root.addGroup("aPGW")


            
    def add_wms(self, usluga, nazwa):
            root = QgsProject.instance().layerTreeRoot()
            global grupa
            grupa = root.addGroup(nazwa)
            for warstwa in usluga:
                    url = ("contextualWMSLegend=0&"
                            "crs=EPSG:2180&"
                            "dpiMode=7&"
                            "format=image/png&"
                            "layers="+ warstwa[0]+"&"
                            "styles=&"
                            "version=1.3.0&"
                            "url="+warstwa[2])
                    layer = QgsRasterLayer(url, warstwa[1], 'wms')
                    layer.setCustomProperty("PGWWP", "wms_pgwwp_layer")
                    self.wms_pgwwp_layer = layer
                    grupa.addLayer(QgsProject.instance().addMapLayer(self.wms_pgwwp_layer, False))
                    #aPGW.addLayer(self.wms_pgwwp_layer)
                    #PGWWP.addLayer(self.wms_pgwwp_layer)
                    self.dlg.pbPGWWP.setEnabled(True)
                    
                    
    def add_group_mphp(self):
            global root
            root = QgsProject.instance().layerTreeRoot()
            global MPHP10k
            MPHP10k = root.addGroup("MPHP10k")
            
    #MPHP10k - cieki szerokie 
    def add_wms_mphp_cieki_s(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=20&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Cieki szerokie (skala od 75k)', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
    #MPHP10k - jeziora 
    def add_wms_mphp_jeziora(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=21&layers=22&"
                    "styles=&styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Jeziora', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
                        
    #MPHP10k - Morza i zatoki 
    def add_wms_mphp_morza(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=23&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Morza i zatoki', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
    #MPHP10k - działy wodne
    def add_wms_mphp_dzialy(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=0&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Działy wodne', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 1      
    def add_wms_mphp_zlewnie1(self):
            #root = QgsProject.instance().layerTreeRoot()
            #MPHP10k = root.addGroup("MPHP10k")
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=1&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 1', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
            
    #MPHP10k - Zlewnie poziomu 2      
    def add_wms_mphp_zlewnie2(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=2&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 2', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 3      
    def add_wms_mphp_zlewnie3(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=3&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 3', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 4      
    def add_wms_mphp_zlewnie4(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=4&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 4', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 5      
    def add_wms_mphp_zlewnie5(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=5&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 5', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 6      
    def add_wms_mphp_zlewnie6(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=6&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 6', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 7      
    def add_wms_mphp_zlewnie7(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=7&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 7', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
                #MPHP10k - Zlewnie poziomu 8      
    def add_wms_mphp_zlewnie8(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=8&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 8', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 9      
    def add_wms_mphp_zlewnie9(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=9&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 9', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 10      
    def add_wms_mphp_zlewnie10(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=10&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 10', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 11      
    def add_wms_mphp_zlewnie11(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=11&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 11', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 12      
    def add_wms_mphp_zlewnie12(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=12&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 12', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 13      
    def add_wms_mphp_zlewnie13(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=13&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 13', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Zlewnie poziomu 14      
    def add_wms_mphp_zlewnie14(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=14&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie poziomu 14', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - zlewnie elementarne      
    def add_wms_mphp_zlew_element(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=15&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Zlewnie elementarne', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)

    #MPHP10k - cieki  
    def add_wms_mphp_cieki(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=16&layers=17&layers=18&"
                    "styles=&styles=&styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Cieki', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - odcinki cieków  
    def add_wms_mphp_odcinki_ciek(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=19&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Odcinki cieków (skala od 75k)', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            

            
    #MPHP10k - Węzły na działach wodnych 
    def add_wms_mphp_wezly_dzial(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=24&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Węzły na działach wodnych', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Węzły na ciekach wyróżnionych 
    def add_wms_mphp_wezly_ciek(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=25&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Węzły na ciekach wyróżnionych', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Sekcje mapy 
    def add_wms_mphp_sekcje(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=26&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Sekcje mapy', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Nazwy cieków 
    def add_wms_mphp_nazwy_ciek(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=27&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Nazwy cieków', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
            
    #MPHP10k - Nazwy jezior 
    def add_wms_mphp_nazwy_jezior(self):
            url = ("contextualWMSLegend=0&"
                    "crs=EPSG:2180&"
                    "dpiMode=7&"
                    "format=image/png&"
                    "layers=28&"
                    "styles=&"
                    "version=1.3.0&"
                    "url=https://wody.isok.gov.pl/gpservices/KZGW/ISOK_MPHP/MapServer/WMSServer")
            layer = QgsRasterLayer(url, 'Nazwy jezior', 'wms')
            layer.setCustomProperty("MPHP10k", "wms_mphp_layer")
            self.wms_mphp_layer = layer
            QgsProject.instance().addMapLayer(self.wms_mphp_layer, False)
            MPHP10k.addLayer(self.wms_mphp_layer)
            self.dlg.pbMPHP.setEnabled(True)
